OBJS = C:\Users\jccooper\maingit\crepo\c-codeRepo\gameProj\Proj2\02_getting_an_image_on_the_screen.cpp
OBJ_NAME = SDLMain

all : $(OBJS)
	g++ $(OBJS) -IC:\mingw_dev_lib\SDL2\include\SDL2 -LC:\mingw_dev_lib\SDL2\lib -w -Wl,-subsystem,windows -lmingw32 -lSDL2main -lSDL2 -o $(OBJ_NAME)